name: run_script
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SWITCHBOT_ACCESS_TOKEN: ${{ secrets.SWITCHBOT_ACCESS_TOKEN }}
          SWITCHBOT_SECRET: ${{ secrets.SWITCHBOT_SECRET }}
          SWITCHBOT_CIRCULATOR_DEVICE_ID: ${{ secrets.SWITCHBOT_CIRCULATOR_DEVICE_ID }}
          SWITCHBOT_CEILING_DEVICE_ID: ${{ secrets.SWITCHBOT_CEILING_DEVICE_ID }}
          SWITCHBOT_FLOOR_DEVICE_ID: ${{ secrets.SWITCHBOT_FLOOR_DEVICE_ID }}
          SWITCHBOT_STUDY_DEVICE_ID: ${{ secrets.SWITCHBOT_STUDY_DEVICE_ID }}
          SWITCHBOT_OUTDOOR_DEVICE_ID: ${{ secrets.SWITCHBOT_OUTDOOR_DEVICE_ID }}
          SWITCHBOT_AIR_CONDITIONER_DEVICE_ID: ${{ secrets.SWITCHBOT_AIR_CONDITIONER_DEVICE_ID }}
          SWITCHBOT_AIR_CONDITIONER_SUPPORT_DEVICE_ID: ${{ secrets.SWITCHBOT_AIR_CONDITIONER_SUPPORT_DEVICE_ID }}
          SWITCHBOT_BASE_URL: ${{ secrets.SWITCHBOT_BASE_URL }}
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          JMA_AREA_NAME: ${{ secrets.JMA_AREA_NAME }}
          JMA_AREA_CODE: ${{ secrets.JMA_AREA_CODE }}
        run: |
          python src/home_climate_control.py
